name: test_beacon
description: A library makes Flutter test more fun
version: 0.1.1
homepage: https://github.com/timnew/test_beacon

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:

flutter:
